<?php
$z[0]=Array("field","",62,90);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",92,130);
$z[1][4]['name']="typename";
$z[2]=Array("field","",196,224);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n							<li>\r\n								<span class=\"date\">[field:pubdate\r\n									function=\"MyDate('m-d',@me)\"/]</span>\r\n								<a href=\"[field:arcurl /]\">[field:title /]</a>\r\n							</li>\r\n							",314,548);
$z[3][4]['titlelen']="60";
$z[3][4]['row']="8";

?>