<?php
$z[0]=Array("field","",49,77);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",79,108);
$z[1][4]['name']="typename";
$z[2]=Array("field","",149,177);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\r\n            <li><span class=\"date\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\r\n          ",265,470);
$z[3][4]['titlelen']="60";
$z[3][4]['row']="8";

?>