
<field:youxiang itemname="登录邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:youxiang>

<field:mima itemname="密码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mima>

<field:mimaqueren itemname="确认密码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mimaqueren>

<field:mingzi itemname="名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mingzi>

<field:国家 itemname="国家" autofield="1" type="select" isnull="true" default="中国,美国,日本,韩国"  maxlength="250" page="">
</field:国家>

<field:dianhua itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dianhua>

<field:dizhi itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dizhi>

<field:shengri itemname="出生年月" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shengri>

<field:gupiao itemname="交易经验-股票" autofield="1" type="radio" isnull="true" default="没有,小于1年,1~2年,2~3年,3~5年"  maxlength="250" page="">
</field:gupiao>

<field:waihui itemname="交易经验-外汇" autofield="1" type="radio" isnull="true" default="没有,小于1年,1~2年,2~3年,3~5年"  maxlength="250" page="">
</field:waihui>
