
<field:mingzi itemname="您的名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mingzi>

<field:dizhi itemname="您的地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dizhi>

<field:nianling itemname="您的年龄" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:nianling>

<field:shouru itemname="您的年收入" autofield="1" type="radio" isnull="true" default="< 10000,10000~24999,25000~499999,50000~99999,100000+"  maxlength="250" page="">
</field:shouru>
