
<field:youxiang itemname="登录邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:youxiang>

<field:mima itemname="密码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mima>

<field:mimaqueren itemname="确认密码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mimaqueren>

<field:mingzi itemname="名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mingzi>
