<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",5,159);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",171,188);
$z[2]=Array("arcurl","",203,218);
$z[3]=Array("title","",234,248);
$z[4]=Array("pubdate","",297,343);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",368,382);
$z[6]=Array("scores","",407,422);
$z[7]=Array("description","",456,476);

?>