<?php
$z[0]=Array("spaceurl","",151,169);
$z[1]=Array("face","",198,211);
$z[2]=Array("spaceurl","",252,270);
$z[3]=Array("uname","",289,303);
$z[4]=Array("spaceurl","",340,358);
$z[5]=Array("spaceurl","",411,429);
$z[6]=Array("spaceurl","",493,511);
$z[7]=Array("rankname","",628,646);
$z[8]=Array("jointime","",708,760);
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",822,875);
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>