<?php
$z[0]=Array("field","",256,275);
$z[0][4]['name']="title";
$z[1]=Array("global","",276,302);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",343,370);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",410,440);
$z[3][4]['name']="cfg_description";
$z[4]=Array("include","",1122,1158);
$z[4][4]['filename']="head.htm";
$z[5]=Array("sql","[field:content/]",1263,1355);
$z[5][4]['sql']="Select * from dede_addon_suipian where aid=2";
$z[6]=Array("include","",1421,1461);
$z[6][4]['filename']="leftside.htm";
$z[7]=Array("field","",1532,1554);
$z[7][4]['name']="typename";
$z[8]=Array("include","",2771,2812);
$z[8][4]['filename']="rightside.htm";
$z[9]=Array("sql","\r\n					<li>\r\n						<a href=\"[field:url/]\" target=\"_blank\">\r\n							<img src=\"[field:logo/]\" width=\"120\" height=\"50\" border=\"0\" />\r\n							<img src=\"[field:logo/]\" width=\"120\" height=\"50\" border=\"0\"\r\n								class=\"hide\" />\r\n						</a>\r\n					</li>\r\n					",3072,3377);
$z[9][4]['sql']="Select * from dede_flink";
$z[10]=Array("include","",3479,3517);
$z[10][4]['filename']="footer.htm";

?>