<?php
$z[0]=Array("spaceurl","",176,194);
$z[1]=Array("face","",232,245);
$z[2]=Array("spaceurl","",301,319);
$z[3]=Array("uname","",338,352);
$z[4]=Array("spaceurl","",404,422);
$z[5]=Array("spaceurl","",483,501);
$z[6]=Array("spaceurl","",573,591);
$z[7]=Array("rankname","",740,758);
$z[8]=Array("jointime","",853,905);
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",1000,1053);
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>