<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"\r\n						<a href='{@me[' arcurl']}' class='preview'>\r\n							<img src='{@me[' litpic']}'/>\r\n						</a>\r\n						\"); ",12,201);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",214,231);
$z[2]=Array("arcurl","",261,276);
$z[3]=Array("title","",292,306);
$z[4]=Array("pubdate","",379,425);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",467,481);
$z[6]=Array("scores","",523,538);
$z[7]=Array("description","",578,598);

?>