
<field:mingzi itemname="名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mingzi>

<field:haoma itemname="证件号码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:haoma>


<field:shouji itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shouji>

<field:zhanghao itemname="MT4账号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:zhanghao>

<field:jine itemname="金额" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:jine>

<field:beizhu itemname="备注" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:beizhu>
