<?php
$z[0]=Array("global","",182,207);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",273,298);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",360,385);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",418,444);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",572,599);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",672,699);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",702,728);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",893,920);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",932,964);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1011,1037);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("myad","",1094,1129);
$z[10][4]['name']="innerTopBanner1";
$z[11]=Array("myad","",1165,1200);
$z[11][4]['name']="innerTopBanner2";
$z[12]=Array("global","",1512,1537);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("channel","\r\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\r\n      	",1578,1823);
$z[13][4]['type']="top";
$z[13][4]['row']="10";
$z[13][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[14]=Array("global","",1919,1944);
$z[14][4]['name']="cfg_cmsurl";
$z[15]=Array("tag","\r\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\r\n          ",2767,2899);
$z[15][4]['row']="10";
$z[15][4]['getall']="1";
$z[15][4]['sort']="month";

?>