<?php
$z[0]=Array("sql","[field:content/]",198,286);
$z[0][4]['sql']="Select * from dede_addon_suipian where aid=1";
$z[1]=Array("channelartlist","\r\n  	 <li class=\"main-menu {dede:field.currentstyle/}\"><a style=\"padding:0px\" class=\"m\" href=\"{dede:field.typedir/}\">{dede:field.typename/}</a> </li>\r\n	 ",1404,1638);
$z[1][4]['typeid']="1,2,3";
$z[1][4]['currentstyle']="current";
$z[2]=Array("channelartlist","\r\n      <li class=\"main-menu {dede:field.currentstyle/}\"> <a style=\"padding:0px\" class=\"m\" href=\"{dede:field.typedir/}\">{dede:field.typename/}<i></i></a> \r\n      <ul class=\"sub-menu\"> \r\n       {dede:channel type='son'}\r\n		<li><a style=\"padding-left:0px 10px\" href=\"[field:typelink /]\" target=\"_self\"><span>></span>[field:typename/]</a> </li>\r\n		{/dede:channel}\r\n      </ul></li>\r\n    ",1645,2115);
$z[2][4]['typeid']="4,12,17,23";
$z[2][4]['currentstyle']="current";

?>