<?php
$z[0]=Array("global","",263,289);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",330,357);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",397,427);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",872,908);
$z[3][4]['filename']="head.htm";
$z[4]=Array("sql","[field:content/]",1396,1485);
$z[4][4]['sql']="Select * from dede_addon_suipian where aid=54";
$z[5]=Array("sql","[field:content/]",3095,3184);
$z[5][4]['sql']="Select * from dede_addon_suipian where aid=46";
$z[6]=Array("sql","[field:content/]",3271,3360);
$z[6][4]['sql']="Select * from dede_addon_suipian where aid=48";
$z[7]=Array("sql","[field:content/]",3385,3474);
$z[7][4]['sql']="Select * from dede_addon_suipian where aid=47";
$z[8]=Array("sql","[field:content/]",3521,3610);
$z[8][4]['sql']="Select * from dede_addon_suipian where aid=49";
$z[9]=Array("sql","[field:content/]",3674,3763);
$z[9][4]['sql']="Select * from dede_addon_suipian where aid=45";
$z[10]=Array("sql","[field:content/]",3831,3920);
$z[10][4]['sql']="Select * from dede_addon_suipian where aid=44";
$z[11]=Array("sql","[field:content/]",4062,4151);
$z[11][4]['sql']="Select * from dede_addon_suipian where aid=43";
$z[12]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">>   [field:title function=\"cn_substr(@me,120)\"/]</a></li>\r\n",4289,4521);
$z[12][4]['typeid']="17";
$z[12][4]['limit']="0,20";
$z[12][4]['titlelen']="120";
$z[12][4]['infolen']="";
$z[12][4]['orderby']="pubdate";
$z[13]=Array("include","",4619,4657);
$z[13][4]['filename']="footer.htm";

?>