
<field:youxiang itemname="登录邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:youxiang>

<field:mima itemname="密码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mima>

<field:mimaqueren itemname="确认密码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mimaqueren>

<field:mingzi itemname="名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mingzi>

<field:国家 itemname="国家" autofield="1" type="select" isnull="true" default="中国,美国,日本,韩国"  maxlength="250" page="">
</field:国家>

<field:dianhua itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dianhua>

<field:dizhi itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dizhi>

<field:shengri itemname="出生年月" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shengri>

<field:gupiao itemname="交易经验-股票" autofield="1" type="radio" isnull="true" default="没有,小于1年,1~2年,2~3年,3~5年"  maxlength="250" page="">
</field:gupiao>

<field:waihui itemname="交易经验-外汇" autofield="1" type="radio" isnull="true" default="没有,小于1年,1~2年,2~3年,3~5年"  maxlength="250" page="">
</field:waihui>

<field:qihuo itemname="交易经验-期货" autofield="1" type="radio" isnull="true" default="没有,小于1年,1~2年,2~3年,3~5年"  maxlength="250" page="">
</field:qihuo>

<field:qiquan itemname="交易经验-期权" autofield="1" type="radio" isnull="true" default="没有,小于1年,1~2年,2~3年,3~5年"  maxlength="250" page="">
</field:qiquan>

<field:heyue itemname="交易经验-差价合约" autofield="1" type="radio" isnull="true" default="没有,小于1年,1~2年,2~3年,3~5年"  maxlength="250" page="">
</field:heyue>

<field:jijin itemname="交易经验-基金" autofield="1" type="radio" isnull="true" default="没有,小于1年,1~2年,2~3年,3~5年"  maxlength="250" page="">
</field:jijin>

<field:shouru itemname="年收入" autofield="1" type="radio" isnull="true" default="< 10000,10000~24999,25000~499999,50000~99999,100000+"  maxlength="250" page="">
</field:shouru>

<field:zichan itemname="净资产" autofield="1" type="radio" isnull="true" default="< 10000,10000~24999,25000~499999,50000~99999,100000+"  maxlength="250" page="">
</field:zichan>

<field:zhidao itemname="你是怎么知道我们" autofield="1" type="select" isnull="true" default="搜索引擎,网页广告,电视广告,经纪人介绍"  maxlength="250" page="">
</field:zhidao>

<field:daima itemname="经纪人代码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:daima>

<field:mt4Account itemname="MT4账户" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mt4Account>
