






<field:shouru itemname="您的年收入" autofield="1" type="radio" isnull="true" default="< 10000,10000~24999,25000~499999,50000~99999,100000+"  maxlength="250" page="">
</field:shouru>

<field:youxiang itemname="您的邮箱地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:youxiang>

<field:shouji itemname="您的真实手机号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shouji>





<field:mingzi1 itemname="您的名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mingzi1>

<field:dizhi1 itemname="您的地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dizhi1>
