<?php
$z[0]=Array("field","",258,277);
$z[0][4]['name']="title";
$z[1]=Array("global","",278,304);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",344,371);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",410,440);
$z[3][4]['name']="cfg_description";
$z[4]=Array("include","",962,998);
$z[4][4]['filename']="head.htm";
$z[5]=Array("sql","[field:content/]",1109,1197);
$z[5][4]['sql']="Select * from dede_addon_suipian where aid=2";
$z[6]=Array("include","",1265,1305);
$z[6][4]['filename']="leftside.htm";
$z[7]=Array("field","",1373,1395);
$z[7][4]['name']="typename";
$z[8]=Array("include","",3972,4013);
$z[8][4]['filename']="rightside.htm";
$z[9]=Array("sql","\n	  <li><a href=\"[field:url/]\" target=\"_blank\"><img src=\"[field:logo/]\" width=\"120\" height=\"50\" border=\"0\" /><img src=\"[field:logo/]\" width=\"120\" height=\"50\" border=\"0\" class=\"hide\" /></a> </li>\n	  ",4274,4524);
$z[9][4]['sql']="Select * from dede_flink";
$z[10]=Array("include","",4617,4655);
$z[10][4]['filename']="footer.htm";

?>