
















<field:mingzi1 itemname="您的名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mingzi1>

<field:dizhi1 itemname="您的地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dizhi1>

<field:nianling1 itemname="您的年龄" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:nianling1>

<field:shouru1 itemname="您的收入" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shouru1>

<field:youxiang1 itemname="您的邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:youxiang1>

<field:shouji1 itemname="您的手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shouji1>
