








<field:youxiang itemname="您的邮箱地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:youxiang>

<field:shouji itemname="您的真实手机号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shouji>





<field:mingzi1 itemname="您的名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mingzi1>

<field:dizhi1 itemname="您的地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dizhi1>

<field:nianling1 itemname="您的年龄" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:nianling1>

<field:shouru1 itemname="您的收入" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shouru1>
