<?php
$z[0]=Array("sql","[field:content/]",114,202);
$z[0][4]['sql']="Select * from dede_addon_suipian where aid=1";
$z[1]=Array("channelartlist","\r\n  	 <li class=\"main-menu {dede:field.currentstyle/}\"><a class=\"m\" href=\"{dede:field.typedir/}\">{dede:field.typename/}</a> </li>\r\n	 ",819,1036);
$z[1][4]['typeid']="35,36,37";
$z[1][4]['currentstyle']="current";
$z[2]=Array("channelartlist","\r\n      <li class=\"main-menu {dede:field.currentstyle/}\"> <a class=\"m\" href=\"{dede:field.typedir/}\">{dede:field.typename/}<i></i></a> \r\n      <ul class=\"sub-menu\"> \r\n       {dede:channel type='son'}\r\n		<li><a href=\"[field:typelink /]\" target=\"_self\"><span>></span>[field:typename/]</a> </li>\r\n		{/dede:channel}\r\n      </ul></li>\r\n    ",1043,1464);
$z[2][4]['typeid']="38,45,47,52";
$z[2][4]['currentstyle']="current";

?>