<?php
$z[0]=Array("sql","[field:content/]",112,200);
$z[0][4]['sql']="Select * from dede_addon_suipian where aid=1";
$z[1]=Array("channelartlist","\r\n  	 <li class=\"main-menu {dede:field.currentstyle/}\"><a class=\"m\" href=\"{dede:field.typedir/}\">{dede:field.typename/}</a> </li>\r\n	 ",769,983);
$z[1][4]['typeid']="1,2,3";
$z[1][4]['currentstyle']="current";
$z[2]=Array("channelartlist","\r\n      <li class=\"main-menu {dede:field.currentstyle/}\"> <a class=\"m\" href=\"{dede:field.typedir/}\">{dede:field.typename/}<i></i></a> \r\n      <ul class=\"sub-menu\"> \r\n       {dede:channel type='son'}\r\n		<li><a href=\"[field:typelink /]\" target=\"_self\"><span>&gt;</span>[field:typename/]</a> </li>\r\n		{/dede:channel}\r\n      </ul></li>\r\n    ",990,1413);
$z[2][4]['typeid']="4,12,17,23";
$z[2][4]['currentstyle']="current";

?>