<?php
$z[0]=Array("global","",263,289);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",330,357);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",397,427);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",872,908);
$z[3][4]['filename']="head.htm";
$z[4]=Array("sql","[field:content/]",3001,3090);
$z[4][4]['sql']="Select * from dede_addon_suipian where aid=46";
$z[5]=Array("sql","[field:content/]",3177,3266);
$z[5][4]['sql']="Select * from dede_addon_suipian where aid=48";
$z[6]=Array("sql","[field:content/]",3291,3380);
$z[6][4]['sql']="Select * from dede_addon_suipian where aid=47";
$z[7]=Array("sql","[field:content/]",3427,3516);
$z[7][4]['sql']="Select * from dede_addon_suipian where aid=49";
$z[8]=Array("sql","[field:content/]",3580,3669);
$z[8][4]['sql']="Select * from dede_addon_suipian where aid=45";
$z[9]=Array("sql","[field:content/]",3737,3826);
$z[9][4]['sql']="Select * from dede_addon_suipian where aid=44";
$z[10]=Array("sql","[field:content/]",3970,4059);
$z[10][4]['sql']="Select * from dede_addon_suipian where aid=43";
$z[11]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">&gt; &nbsp; [field:title function=\"cn_substr(@me,120)\"/]</a></li>\r\n",4191,4430);
$z[11][4]['typeid']="17";
$z[11][4]['limit']="0,20";
$z[11][4]['titlelen']="120";
$z[11][4]['infolen']="";
$z[11][4]['orderby']="pubdate";
$z[12]=Array("include","",4528,4566);
$z[12][4]['filename']="footer.htm";

?>