<?php
$z[0]=Array("global","",263,292);
$z[0][4]['name']="cfg_webname_en";
$z[1]=Array("global","",333,360);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",400,430);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",878,917);
$z[3][4]['filename']="head_en.htm";
$z[4]=Array("sql","[field:content/]",1408,1497);
$z[4][4]['sql']="Select * from dede_addon_suipian where aid=91";
$z[5]=Array("sql","[field:content/]",3109,3198);
$z[5][4]['sql']="Select * from dede_addon_suipian where aid=92";
$z[6]=Array("sql","[field:content/]",3285,3374);
$z[6][4]['sql']="Select * from dede_addon_suipian where aid=93";
$z[7]=Array("sql","[field:content/]",3399,3488);
$z[7][4]['sql']="Select * from dede_addon_suipian where aid=94";
$z[8]=Array("sql","[field:content/]",3535,3624);
$z[8][4]['sql']="Select * from dede_addon_suipian where aid=95";
$z[9]=Array("sql","[field:content/]",3688,3777);
$z[9][4]['sql']="Select * from dede_addon_suipian where aid=96";
$z[10]=Array("sql","[field:content/]",3845,3934);
$z[10][4]['sql']="Select * from dede_addon_suipian where aid=97";
$z[11]=Array("sql","[field:content/]",4076,4165);
$z[11][4]['sql']="Select * from dede_addon_suipian where aid=98";
$z[12]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">>   [field:title function=\"cn_substr(@me,120)\"/]</a></li>\r\n",4321,4553);
$z[12][4]['typeid']="47";
$z[12][4]['limit']="0,20";
$z[12][4]['titlelen']="120";
$z[12][4]['infolen']="";
$z[12][4]['orderby']="pubdate";
$z[13]=Array("include","",4651,4692);
$z[13][4]['filename']="footer_en.htm";

?>