<?php
$z[0]=Array("global","",259,288);
$z[0][4]['name']="cfg_webname_en";
$z[1]=Array("global","",328,355);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",394,424);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",859,898);
$z[3][4]['filename']="head_en.htm";
$z[4]=Array("sql","[field:content/]",1368,1457);
$z[4][4]['sql']="Select * from dede_addon_suipian where aid=91";
$z[5]=Array("sql","[field:content/]",3028,3117);
$z[5][4]['sql']="Select * from dede_addon_suipian where aid=92";
$z[6]=Array("sql","[field:content/]",3200,3289);
$z[6][4]['sql']="Select * from dede_addon_suipian where aid=93";
$z[7]=Array("sql","[field:content/]",3312,3401);
$z[7][4]['sql']="Select * from dede_addon_suipian where aid=94";
$z[8]=Array("sql","[field:content/]",3445,3534);
$z[8][4]['sql']="Select * from dede_addon_suipian where aid=95";
$z[9]=Array("sql","[field:content/]",3594,3683);
$z[9][4]['sql']="Select * from dede_addon_suipian where aid=96";
$z[10]=Array("sql","[field:content/]",3747,3836);
$z[10][4]['sql']="Select * from dede_addon_suipian where aid=97";
$z[11]=Array("sql","[field:content/]",3970,4059);
$z[11][4]['sql']="Select * from dede_addon_suipian where aid=98";
$z[12]=Array("arclist","\n<li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">>   [field:title function=\"cn_substr(@me,120)\"/]</a></li>\n",4209,4439);
$z[12][4]['typeid']="47";
$z[12][4]['limit']="0,20";
$z[12][4]['titlelen']="120";
$z[12][4]['infolen']="";
$z[12][4]['orderby']="pubdate";
$z[13]=Array("include","",4529,4570);
$z[13][4]['filename']="footer_en.htm";

?>