<?php
$z[0]=Array("global","",259,285);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",325,352);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",391,421);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",853,889);
$z[3][4]['filename']="head.htm";
$z[4]=Array("sql","[field:content/]",1356,1445);
$z[4][4]['sql']="Select * from dede_addon_suipian where aid=54";
$z[5]=Array("sql","[field:content/]",3042,3131);
$z[5][4]['sql']="Select * from dede_addon_suipian where aid=46";
$z[6]=Array("sql","[field:content/]",3214,3303);
$z[6][4]['sql']="Select * from dede_addon_suipian where aid=48";
$z[7]=Array("sql","[field:content/]",3326,3415);
$z[7][4]['sql']="Select * from dede_addon_suipian where aid=47";
$z[8]=Array("sql","[field:content/]",3459,3548);
$z[8][4]['sql']="Select * from dede_addon_suipian where aid=49";
$z[9]=Array("sql","[field:content/]",3608,3697);
$z[9][4]['sql']="Select * from dede_addon_suipian where aid=45";
$z[10]=Array("sql","[field:content/]",3761,3850);
$z[10][4]['sql']="Select * from dede_addon_suipian where aid=44";
$z[11]=Array("sql","[field:content/]",3986,4075);
$z[11][4]['sql']="Select * from dede_addon_suipian where aid=43";
$z[12]=Array("arclist","\n<li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">>   [field:title function=\"cn_substr(@me,120)\"/]</a></li>\n",4201,4431);
$z[12][4]['typeid']="17";
$z[12][4]['limit']="0,20";
$z[12][4]['titlelen']="120";
$z[12][4]['infolen']="";
$z[12][4]['orderby']="pubdate";
$z[13]=Array("include","",4521,4559);
$z[13][4]['filename']="footer.htm";

?>